gym/urls.py
from django.urls import path, include
from . import views

app_name = 'gym'

urlpatterns= [
        path('', views.IndexView.as_view(), name='index'),
        path('<int:pk>/', views.DetailView.as_view(), name='detail'),
        path('create/', views.CreateWorkout.as_view(), name='create'),
        path('active_workout/', views.ActiveWorkout.as_view(), name='active_workout'),
        path('finish/', views.finish, name='finish'),
        path('new_exercise/', views.CreateExercise.as_view(), name='new_exercise'),
        path('delete_exercise/<int:pk>', views.DeleteExercise.as_view(),name='delete_exercise'),
        path('all_workouts/', views.AllWorkouts.as_view(), name='all'),

    ]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('gym/', include('gym.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todolist/urls.py
from django.urls import path, include

from . import views

app_name = 'todolist'

urlpatterns = [
        path('', views.IndexView.as_view(), name='index'),
        path('<int:pk>/', views.DetailView.as_view(), name='detail'),
        path('<int:pk>/edit/', views.EditView.as_view(), name='edit'),
        path('<int:pk>/delete/', views.ItemDeleteView.as_view(), name='delete'),
        path('finished/', views.FinishedItemView.as_view(), name='finished'),
        path('create/', views.ItemCreateView.as_view(), name='create'),
        path('signup/', views.SignUpView.as_view(), name='signup'),
        path('profile/', views.profile, name='profile'),
        path('change_password/', views.ChangePassword.as_view(),
            name='pass_change'),
    ]

todolist/models.py
from django.conf import settings
from django.db import models
import datetime
from django.utils import timezone
from PIL import Image

class Todo(models.Model):
    LEVEL_OF_IMPORTANCE = (
            ('!', 'Low'),
            ('!!', 'Medium'),
            ('!!!', 'High'),
        )
    
    title = models.CharField(max_length=50, unique_for_date="due_date")
    body = models.TextField(blank=True)
    due_date = models.DateTimeField(null=True,blank=True)
    importance = models.CharField(max_length=3, choices=LEVEL_OF_IMPORTANCE)
    finished = models.BooleanField(default=False) 
    usr = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='my_todos')
    shared_with = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='shared_with_me') 
    time_since_modified = models.DateTimeField(auto_now=True)
    user_last_change = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='lastly_changed', null=True)
    image = models.ImageField(default='todo.jpeg',upload_to='todo_attachments')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        
        if img.height > 100 or img.width > 100:
            new_img = (200, 200)
            img.thumbnail(new_img)
            img.save(self.image.path)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE)
    avatar = models.ImageField(default='default.jpg',
            upload_to='profile_images')
    bio = models.CharField(max_length=200)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.avatar.path)

        if img.height > 100 or img.width > 100:
            new_img = (200,200)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

todolist/forms.py
from django.contrib.auth import get_user_model
from django import forms

from .models import Todo, Profile

class ItemCreateForm(forms.ModelForm):
    share_with = forms.CharField(required=False)

    class Meta:
        model = Todo
        fields = ['title', 'body', 'importance', 'due_date','share_with',
                'image']

    def clean_shared_with(self):
        User = get_user_model()
        share_with = self.cleaned_data.get('share_with')
        try:
            return User.objects.get(username=share_with)
        except User.DoesNotExist:
            raise forms.ValidationError("No user exists with that username")
        

class MyOwnSignUpForm(forms.ModelForm):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput, label="Password")
    password2 = forms.CharField(widget=forms.PasswordInput, label="Validate Password", help_text="Enter the same password as above")
    email = forms.EmailField(widget=forms.EmailInput, label="Please enter your email address")
    
    error_messages = {
            'password_mismatch': ("The two password fields didn't match."),
    }

    class Meta:
        model = get_user_model()
        fields = ['username']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2


    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


#class ItemCreateForm(forms.ModelForm):
#    class Meta:
#        model = Todo
#        fields = ['title', 'body', 'importance', 'due_date']


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email']

class UpdateProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']
        

todolist/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.decorators import login_required

from .models import Todo
from .forms import MyOwnSignUpForm, ItemCreateForm, UpdateProfileForm,UpdateUserForm


class ChangePassword(PasswordChangeView):
    template_name = 'todolist/change_password.html'
    success_url = reverse_lazy('todolist:profile')


#if method is post we send data to form (request.POST) but we have an image
# aswell so (request.FILES) sends that
@login_required
def profile(request):
    if request.method == "POST":
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance = request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has updated succesfully')
            return HttpResponseRedirect(request.get_full_path())
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)
    
    return render(request, 'todolist/profile.html', {'user_form':user_form, 'profile_form':profile_form})



class ThisIsMineGTFO(UserPassesTestMixin):
    """
    Allows users that are creators and users that have a shared item with them
    to modify and delete items
    """
    def test_func(self):
        obj = self.get_object()
        return obj.usr == self.request.user or self.request.user in obj.shared_with.all()
    #self.request.user.shared_with_me.filter(id=obj.id).exists()

class SignUpView(generic.CreateView):
    form_class = MyOwnSignUpForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class IndexView(generic.ListView):
    """
    Displays all current todo items
    """
    model = Todo
    template_name = 'todolist/index.html'
    context_object_name = 'ordered_todo_items'
    queryset = Todo.objects.order_by('due_date','-importance')


class FinishedItemView(LoginRequiredMixin, generic.ListView):
    """
    Displays all finished items
    """
    model = Todo
    template_name = 'todolist/finished.html'
    context_object_name = 'ordered_todo_items'
    queryset = Todo.objects.order_by('due_date')


class DetailView(LoginRequiredMixin, generic.DetailView):
    """
    Displays a detail page of an item
    """
    model = Todo
    template_name = 'todolist/detail.html'
    context_object_name = 'item'


class EditView(LoginRequiredMixin, ThisIsMineGTFO ,generic.UpdateView):
    """
    Allows each user to modify previously created items
    """
    model = Todo
    fields = ['title', 'body', 'importance', 'due_date', 'finished', 'image']
    template_name = 'todolist/edit.html'
    context_object_name = 'item'
    success_url = reverse_lazy('todolist:index')
    

    def form_valid(self, form):
        lastly = form.instance
        lastly.user_last_change = self.request.user
        return super().form_valid(form)
        


class ItemDeleteView(LoginRequiredMixin, ThisIsMineGTFO, generic.DeleteView):
    """
    Allows each user to delete previously created items
    """
    model = Todo
    template_name = 'todolist/delete.html'
    context_object_name = 'item'
    success_url = reverse_lazy('todolist:index')


class ItemCreateView(LoginRequiredMixin, generic.CreateView):
    """
    Allows a user to create a todo item and possibly share it with other
    users
    """
    model = Todo
    template_name = 'todolist/create.html'
    form_class = ItemCreateForm
    context_object_list = 'item'
    success_url = reverse_lazy('todolist:index')

    def form_valid(self, form):
        todo = form.instance
        todo.usr = self.request.user
        todo.save()
        username=form.cleaned_data['share_with']
        obj = get_user_model()
        try:
            obj.objects.get(username=username)
            todo.shared_with.add(
                    obj.objects.get(username=username)
            )
        except get_user_model().DoesNotExist:
            obj = None
        
        return super().form_valid(form)


#class ItemCreateView(generic.TemplateView):
 #   """Non-generic :)"""
  #  template_name = 'todolist/create.html'
#
 #   def dispatch(self, request, *args, **kwargs):
  #      if request.user.is_authenticated:
   #         return super().dispatch(request, *args, **kwargs)
    #    return HttpResponseRedirect(reverse_lazy('login'))
#
 #   def get_context_data(self, **kwargs):
  #      context = super().get_context_data(**kwargs)
   #     context['form'] = ItemCreateForm()
    #    return context
#
 #   def post(self, request, *args, **kwargs):
  #form = ItemCreateForm(data=request.POST)
   #     todo = form.save(commit=False)
    #    todo.usr = self.request.user
     #   todo.save()
      #  return HttpResponseRedirect(reverse_lazy('todolist:index'))

todolist/templates/todolist/change_password.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save changes">
</form>

todolist/templates/todolist/create.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <p>YYYY-MM-DD HH:MM</p>
    <input type="submit" value="Add the item">
</form>

todolist/templates/todolist/delete.html
<form action="{{ request.get_full_path }}" method='post'>
    {% csrf_token %}
    <p> Are you sure you want to delete "{{ item }}"?</p>
    <input type="submit" value="Confirm!">
</form>

todolist/templates/todolist/detail.html
<fieldset>
    <legend><h1> {{ item.title }}</h1></legend>
    <p>Additional Info: {{ item.body }}</p>
    <p>Attachment: {{ item.image }}</p>

    <div style="background-color: #000000; color: #FFFFFF; padding: 5px;">
        <p>Importance - {{ item.importance }}</p>
    </div>

    <form method="post" enctype="multipart/form-data">
    <img class="rounded-circle account-img" src="{{ item.image.url }} " style="cursor: pointer;"/>
</fieldset>



<div>
    <form action="{% url 'todolist:index' %}" method="get">
        {% csrf_token %}
        <button type="submit">Back to index page</button>
    </form>
</div>


{% if item.finished == False %}
<fieldset>
    <a href="{% url 'todolist:edit' item.id %}">Edit item</a>
    |-----|
    <a href="{% url 'todolist:delete' item.id %}">Delete item</a>
</fieldset>
{% endif %}

todolist/templates/todolist/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save changes">
</form>

todolist/templates/todolist/finished.html
{% if ordered_todo_items %}
<ul>
    {% for item in ordered_todo_items %}
    {% if item.finished == True %}
    {% if request.user == item.usr %}
    <li><a href= "{% url 'todolist:detail' item.id %}" title="To item">{{ item.title }}</a>
        <p>Was due -- {{ item.due_date }}</p></li>
    {% endif %}
    {% endif %}
    {% endfor %}
</ul>
{% else %}
<p>No finished items!</p>
{% endif %}


<fieldset>
    <legend>Shared with me</legend>
    {% for shared_item in request.user.shared_with_me.all %}
    {% if shared_item.finished == True %}
    <ul>
        <li><a href="{% url 'todolist:detail' shared_item.id %}" title="View item">{{ shared_item.title }}</a>
            <p> Shared By: {{ shared_item.usr }}</p></li>
    </ul>
    {% endif %}
    {% endfor %}
</fieldset>

<a href="{% url 'todolist:index' %}">Back to todolist</a>

todolist/templates/todolist/index.html
{% if user.is_authenticated %}
<h1>Hi {{ user.username }}!</h1>

<a href="{% url 'todolist:profile' %}">Profile</a>
<p><a href="{% url 'logout' %}">Log out</a></p>

<fieldset><legend>My items</legend>
{% if ordered_todo_items %}
<ul>
    {% for item in ordered_todo_items %}
    {% if not item.finished %}
    {% if request.user == item.usr %}
    <li><a href= "{% url 'todolist:detail' item.id %}" title="View item">{{ item.title }}</a>
        <p>Due date -- {{ item.due_date }}</p>
        <p>Last modified -- {{ item.time_since_modified }} by {{ item.user_last_change }}</p></li>
    {% endif %}
    {% endif %}
    {% endfor %}
</fieldset>

</ul>
{% else %}
<p>Nothing To-do!</p>
{% endif %}

<fieldset>
    <div>
        <a href="{% url 'todolist:create' %}">Create new item</a>
    </div>
</fieldset>

<fieldset>
    <a href="{% url 'todolist:finished'%}">Finished items</a>
</fieldset>

    
<fieldset>
    <legend>Shared with me</legend>
    {% for shared_item in request.user.shared_with_me.all %}
    <ul>
        <li><a href="{% url 'todolist:detail' shared_item.id %}" title="View item">{{ shared_item.title }}</a>
            <p> Shared By: {{ shared_item.usr }}</p></li>
        <p>Last modified -- {{ shared_item.time_since_modified }} by {{ shared_item.user_last_change }}</p></li>
            
    </ul>
    {% endfor %}
</fieldset>


{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a>
<p>Sign up!</p>
<a href="{% url 'todolist:signup' %}">Sign Up</a>

{% endif %}

todolist/templates/todolist/profile.html
{% csrf_token %}
    <div class="row my-3 p-3">
        <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }} " style="cursor: pointer;"/>
    </div>
    {% if user_form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in user_form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <div class="form-content">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="small mb-1">Username:</label>
                            {{ user_form.username }}
                        <label class="small mb-1">Email:</label>
                            {{ user_form.email }}
                    </div>
                    <div class="form-group">
                        <a href="{% url 'todolist:pass_change' %}">Change Password</a>
                        <hr>
                        <label class="small mb-1">Change Avatar:</label>
                        {{ profile_form.avatar }}
                    </div>
                    <label class="small mb-1">Bio:</label> {{ profile_form.bio }}
                </div>
            </div>
            <br><br>
            <button type="submit" class="btn btn-dark btn-lg">Save Changes</button>
        </form>
    </div>

    <p><a href="{% url 'todolist:index' %}">Todolist</a></p>
    <p><a href="{% url 'gym:index' %}">Gym</a></p>