gym/urls.py
from django.urls import path, include
from . import views

app_name = 'gym'

urlpatterns= [
        path('', views.IndexView.as_view(), name='index'),
        path('<int:pk>/', views.DetailView.as_view(), name='detail'),
        path('create/', views.CreateWorkout.as_view(), name='create'),
        path('active_workout/', views.ActiveWorkout.as_view(), name='active_workout'),
        path('finish/', views.finish, name='finish'),
        path('new_exercise/', views.CreateExercise.as_view(), name='new_exercise'),
        path('delete_exercise/<int:pk>', views.DeleteExercise.as_view(),name='delete_exercise'),
        path('all_workouts/', views.AllWorkouts.as_view(), name='all'),

    ]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('gym/', include('gym.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todolist/urls.py
from django.urls import path, include

from . import views

app_name = 'todolist'

urlpatterns = [
        path('', views.IndexView.as_view(), name='index'),
        path('<int:pk>/', views.DetailView.as_view(), name='detail'),
        path('<int:pk>/edit/', views.EditView.as_view(), name='edit'),
        path('<int:pk>/delete/', views.ItemDeleteView.as_view(), name='delete'),
        path('finished/', views.FinishedItemView.as_view(), name='finished'),
        path('create/', views.ItemCreateView.as_view(), name='create'),
        path('signup/', views.SignUpView.as_view(), name='signup'),
        path('profile/', views.profile, name='profile'),
        path('change_password/', views.ChangePassword.as_view(),
            name='pass_change'),
    ]

gym/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Workout(models.Model):
    title = models.CharField(max_length=50)
    date = models.DateTimeField(default=timezone.now(), blank=True, null=True)
    done = models.BooleanField(default=False)
    usr = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.title)


class Exercise(models.Model):
    exercise_name = models.CharField(max_length=200)
    usr = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    MUSCLE_TYPE = (
            ('Back', 'Back'),
            ('Chest', 'Chest'),
            ('Shoulders', 'Shoulders'),
            ('Legs', 'Legs'),
            ('Bicep', 'Bicep'),
            ('Tricep', 'Tricep'),
            ('Forearm', 'Forearm'),
        )

    muscle = models.CharField(max_length=10, choices=MUSCLE_TYPE)

    def __str__(self):
        return str(self.exercise_name)



class Reps(models.Model):
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE, null=True)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    rep_count = models.CharField(max_length=200)
    kg = models.DecimalField(max_digits=6, decimal_places=2)

    

gym/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Workout, Exercise, Reps



class IndexView(generic.ListView):
    """
    Lists last five finished workouts ordered by date, Lists all exercises.
    """
    model = Workout
    template_name = 'gym/index.html'
    context_object_name = 'gym_items'
    queryset = Workout.objects.order_by('-date')[:5]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['show_exercises'] = Exercise.objects.all().order_by('muscle')
        #To display exercise list
        context['has_open_workout'] = Workout.objects.filter(done=False).exists()
        #To verify if workout in progress
        return context

    def num_of_workouts(self):
        return Workout.objects.filter(done=True).count()

class AllWorkouts(generic.ListView):
    """
    Lists all finished exercises
    """
    model = Workout
    template_name = 'gym/all.html'
    queryset = Workout.objects.order_by('-date')


class DetailView(LoginRequiredMixin, generic.DetailView):
    """
    Displays a detail page of the workout
    """
    model = Workout
    template_name = 'gym/detail.html'
    context_object_name = 'gym_item'



class CreateExercise(LoginRequiredMixin, generic.CreateView):
    """
    Allows users to create exercises
    """
    model = Exercise
    fields = ['exercise_name', 'muscle']
    template_name = 'gym/new_exercise.html'
    success_url = reverse_lazy('gym:index')

    def form_valid(self, form):
        gym = form.instance
        gym.usr = self.request.user 
        return super().form_valid(form)



class DeleteExercise(LoginRequiredMixin, UserPassesTestMixin,generic.DeleteView):
    """
    Allows users to delete previously created exercises
    """
    model = Exercise
    context_object_name = 'item'
    template_name = 'gym/delete.html'
    success_url = reverse_lazy('gym:index')

    def test_func(self):
        obj = self.get_object()
        return obj.usr == self.request.user


class CreateWorkout(LoginRequiredMixin, generic.CreateView):
    """
    Allows users to create a new workout
    """
    def get(request, *args, **kwargs):
        if Workout.objects.filter(done=False):
            return HttpResponseRedirect(reverse_lazy('gym:active_workout'))
        return super().get(*args, **kwargs)
    #Redirection if user tries to create a workout when one exists

    model = Workout
    fields = ['title','date']
    template_name = 'gym/create.html'
    success_url = reverse_lazy('gym:active_workout')


    def form_valid(self, form):
        gym = form.instance
        gym.usr = self.request.user 
        return super().form_valid(form)



class ActiveWorkout(LoginRequiredMixin, UserPassesTestMixin , generic.CreateView):
    """
    Allows users to add specifications about the workout
    """
    model = Reps
    fields = ['exercise','rep_count','kg']
    template_name = 'gym/active_workout.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reps'] = Reps.objects.all()
        return context

    def get_success_url(self):
        return self.request.path

    def test_func(self):
        obj = self.get_object()
        return obj.usr == self.request.user



def finish(request):
    """
    Allows users to finish a workout
    """
    if Workout.objects.get(done=False):
        Workout.objects.update(done=True)
    return HttpResponseRedirect(reverse_lazy('gym:index'))

gym/templates/gym/active_workout.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add exercise">
</form>

<fieldset><legend>Already Pumped</legend>
    {% for i in reps %}
    <li>{{ i.exercise }} - {{ i.kg }}kg for {{ i.rep_count }}Reps</li>
    {% endfor %}
</fieldset> 

<form action="{% url 'gym:finish' %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Finish Pump!">
</form>

gym/templates/gym/all.html
<fieldset><legend>My Workouts</legend>
{% if object_list %}
<ul>
    {% for item in object_list %}
    {% if item.done %}
    {% if request.user == item.usr %}
    <li><a href= "{% url 'gym:detail' item.id %}" title="View item">{{ item.title }}</a></li>
    {% endif %}
    {% endif %}
    {% endfor %}
    {% endif %}
</fieldset>

<a href="{% url 'gym:index' %}">Back</a>

gym/templates/gym/create.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Pump hard!">
</form>

gym/templates/gym/delete.html
<form action="{{ request.get_full_path }}" method='post'>
    {% csrf_token %}
    <p> Are you sure you want to delete "{{ item }}"?</p>
    <input type="submit" value="Confirm!">
</form>

gym/templates/gym/detail.html
<fieldset>
    <legend><h1> {{ gym_item.title }}</h1></legend>
    <p>Date: {{ gym_item.date }}</p>
</fieldset>


<fieldset><legend>Pumped:</legend>
    {% for i in reps %}
    <li>{{ i.exercise }} - {{ i.kg }}kg for {{ i.rep_count }}Reps</li>
    {% endfor %}
</fieldset> 

<div>
    <form action="{% url 'gym:index' %}" method="get">
        {% csrf_token %}
        <button type="submit">Back to Workouts</button>
    </form>
</div>

gym/templates/gym/finish.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Finish Pump!">
</form>

gym/templates/gym/index.html
{% if user.is_authenticated %}
<h1>Hi {{ user.username }}!<a href="{% url 'logout' %}">Log out</a></h1>

<h2><a href="{% url 'todolist:profile' %}">Profile</a></h2>
<h2>
{% if not has_open_workout %}
<p><a href="{% url 'gym:create' %}">Create New Workout</a></p>
{% else %}
<p><a href="{% url 'gym:active_workout' %}">Continue Workout</a></p>
{% endif %}
</h2>

<fieldset><legend>Last '5' Workouts</legend>
{% if gym_items %}
<ul>
    {% for item in gym_items %}
    {% if item.done %}
    {% if request.user == item.usr %}
    <li><a href= "{% url 'gym:detail' item.id %}" title="View item">{{ item.title }}</a>
        <p>{{ item.date }}</p></li>
    {% endif %}
    {% endif %}
    {% endfor %}
    <p><a href="{% url 'gym:all' %}">All Workouts</a></p>
</fieldset>

<h2><a href="{% url 'gym:new_exercise' %}">Add an Exercise</a></h2>


<fieldset>
    <legend>My Exercises</legend>

    {% for i in show_exercises %}
    {% if request.user == i.usr %}
    <li>{{ i }} <a href="{% url 'gym:delete_exercise' i.id %}">Delete Exercise</a></li>
    {% endif %}
    {% endfor %}
</fieldset>


</ul>
{% else %}
<p>No Workouts!</p>
{% endif %}



{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a>
<p>Sign up!</p>
<a href="{% url 'todolist:signup' %}">Sign Up</a>
{% endif %}

gym/templates/gym/new_exercise.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add exercise">
</form>